# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-24 08:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnchorDxLimsApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='department',
            field=models.CharField(default='null', max_length=32),
            preserve_default=False,
        ),
    ]
