# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-02 04:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnchorDxLimsApp', '0002_userinfo_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='clinicalSampleInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('department', models.CharField(max_length=32)),
                ('sam_code_num', models.CharField(max_length=32)),
                ('PatientName', models.CharField(max_length=32)),
                ('PatientAge', models.CharField(max_length=32)),
                ('PatientSex', models.CharField(max_length=32)),
                ('PatientBirthday', models.CharField(max_length=32)),
                ('PatientPhoneNumber', models.CharField(max_length=32)),
                ('PatientEmail', models.CharField(max_length=32)),
                ('PatientAddress', models.CharField(max_length=32)),
                ('treatment_hospital', models.CharField(max_length=32)),
                ('treatment_department', models.CharField(max_length=32)),
                ('AttendingDoctor', models.CharField(max_length=32)),
                ('DoctorEmail', models.CharField(max_length=32)),
                ('Pathological_diagnosis', models.CharField(max_length=32)),
                ('clinical_diagnosis', models.CharField(max_length=32)),
                ('Clinical_stage', models.CharField(max_length=32)),
                ('is_tubercle_history', models.CharField(max_length=32)),
                ('tubercle_distribution', models.CharField(max_length=32)),
                ('sample_source', models.CharField(max_length=32)),
                ('acquisition_time', models.CharField(max_length=32)),
                ('family_history', models.CharField(max_length=32)),
                ('receiving_time', models.CharField(max_length=32)),
                ('sample_count', models.CharField(max_length=32)),
                ('sample_type', models.CharField(max_length=32)),
                ('sample_type_text', models.CharField(max_length=32)),
                ('infection_history', models.CharField(max_length=32)),
                ('detected_gene_time', models.CharField(max_length=32)),
                ('detected_gene_name', models.CharField(max_length=32)),
                ('detected_gene_result', models.CharField(max_length=32)),
                ('treatment_history_surgery', models.CharField(max_length=32)),
                ('treatment_history_chem', models.CharField(max_length=32)),
                ('treatment_history_therapy', models.CharField(max_length=32)),
                ('contract_name', models.CharField(max_length=32)),
                ('contract_pay', models.CharField(max_length=32)),
                ('pay_way', models.CharField(max_length=32)),
                ('pos_code', models.CharField(max_length=32)),
                ('Client', models.CharField(max_length=32)),
                ('remarks', models.CharField(max_length=32)),
                ('cancer_type', models.CharField(max_length=32)),
                ('detection_type', models.CharField(max_length=32)),
                ('product_name', models.CharField(max_length=32)),
                ('is_return', models.CharField(max_length=32)),
                ('is_invoice', models.CharField(max_length=32)),
            ],
        ),
    ]
