# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-14 02:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnchorDxLimsApp', '0006_clinicalsampleinfopass'),
    ]

    operations = [
        migrations.CreateModel(
            name='clinicalSampleInfoNotPass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64)),
                ('department', models.CharField(max_length=64)),
                ('sam_code_num', models.CharField(max_length=64)),
                ('PatientName', models.CharField(max_length=64)),
                ('PatientAge', models.CharField(max_length=32)),
                ('PatientSex', models.CharField(max_length=32)),
                ('PatientBirthday', models.CharField(max_length=64)),
                ('PatientPhoneNumber', models.CharField(max_length=64)),
                ('PatientEmail', models.CharField(max_length=64)),
                ('PatientAddress', models.CharField(max_length=256)),
                ('treatment_hospital', models.CharField(max_length=128)),
                ('treatment_department', models.CharField(max_length=64)),
                ('AttendingDoctor', models.CharField(max_length=64)),
                ('DoctorEmail', models.CharField(max_length=64)),
                ('Pathological_diagnosis', models.CharField(max_length=256)),
                ('clinical_diagnosis', models.CharField(max_length=256)),
                ('Clinical_stage', models.CharField(max_length=32)),
                ('is_tubercle_history', models.CharField(max_length=32)),
                ('tubercle_distribution', models.CharField(max_length=256)),
                ('sample_source', models.CharField(max_length=256)),
                ('acquisition_time', models.CharField(max_length=32)),
                ('family_history', models.CharField(max_length=128)),
                ('receiving_time', models.CharField(max_length=32)),
                ('sample_count', models.CharField(max_length=32)),
                ('sample_type', models.CharField(max_length=64)),
                ('sample_type_text', models.CharField(max_length=256)),
                ('infection_history', models.CharField(max_length=256)),
                ('detected_gene_time', models.CharField(max_length=32)),
                ('detected_gene_name', models.CharField(max_length=128)),
                ('detected_gene_result', models.CharField(max_length=256)),
                ('treatment_history_surgery', models.CharField(max_length=256)),
                ('treatment_history_chem', models.CharField(max_length=256)),
                ('treatment_history_therapy', models.CharField(max_length=256)),
                ('contract_name', models.CharField(max_length=64)),
                ('contract_pay', models.CharField(max_length=64)),
                ('pay_way', models.CharField(max_length=64)),
                ('pos_code', models.CharField(max_length=64)),
                ('Client', models.CharField(max_length=32)),
                ('remarks', models.CharField(max_length=512)),
                ('cancer_type', models.CharField(max_length=128)),
                ('detection_type', models.CharField(max_length=256)),
                ('product_name', models.CharField(max_length=128)),
                ('is_return', models.CharField(max_length=32)),
                ('is_invoice', models.CharField(max_length=32)),
                ('ExperimentNumber', models.CharField(max_length=128)),
                ('CollectSamplesDate', models.CharField(max_length=256)),
                ('Reason', models.CharField(max_length=512)),
            ],
        ),
        migrations.AddField(
            model_name='clinicalsampleinfopass',
            name='Reason',
            field=models.CharField(default='1', max_length=512),
            preserve_default=False,
        ),
    ]
