# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-14 02:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AnchorDxLimsApp', '0007_auto_20170814_1040'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='clinicalSampleInfoPass',
            new_name='clinicalSampleInfo_Not_Pass',
        ),
        migrations.RenameModel(
            old_name='clinicalSampleInfoNotPass',
            new_name='clinicalSampleInfo_Pass',
        ),
    ]
