# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-23 08:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnchorDxLimsApp', '0008_auto_20170814_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicalsampleinfo',
            name='contract_review',
            field=models.CharField(default=0, max_length=16),
            preserve_default=False,
        ),
    ]
