# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-30 07:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnchorDxLimsApp', '0009_clinicalsampleinfo_contract_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicalsampleinfo',
            name='CollectSamplesDate',
            field=models.CharField(default=0, max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clinicalsampleinfo',
            name='ExperimentNumber',
            field=models.CharField(default=0, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clinicalsampleinfo',
            name='Reason',
            field=models.CharField(default=0, max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clinicalsampleinfo',
            name='Receivables',
            field=models.CharField(default=0, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clinicalsampleinfo',
            name='ReceivablesDate',
            field=models.CharField(default=0, max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clinicalsampleinfo',
            name='contractReviewReason',
            field=models.CharField(default=0, max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clinicalsampleinfo',
            name='sample_review',
            field=models.CharField(default=0, max_length=16),
            preserve_default=False,
        ),
    ]
