# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-08 06:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnchorDxLimsApp', '0010_auto_20170830_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicalsampleinfo',
            name='task_assignment',
            field=models.CharField(default='', max_length=16),
            preserve_default=False,
        ),
    ]
