# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-11 03:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnchorDxLimsApp', '0011_clinicalsampleinfo_task_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicalsampleinfo',
            name='TaskReceiver',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clinicalsampleinfo',
            name='taskRemarks',
            field=models.CharField(default='', max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clinicalsampleinfo',
            name='taskTime',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
    ]
