# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-13 08:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnchorDxLimsApp', '0012_auto_20170911_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicalsampleinfo',
            name='TaskProgress',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
    ]
