# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-18 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnchorDxLimsApp', '0014_auto_20170914_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='dnaextractinfo',
            name='DNA_extraction_num',
            field=models.CharField(default=1, max_length=16),
            preserve_default=False,
        ),
    ]
