# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-20 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnchorDxLimsApp', '0015_dnaextractinfo_dna_extraction_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='dnaextractinfo',
            name='DNA_extraction_review_Sign',
            field=models.CharField(default=0, max_length=16),
            preserve_default=False,
        ),
    ]
