# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-29 06:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnchorDxLimsApp', '0016_dnaextractinfo_dna_extraction_review_sign'),
    ]

    operations = [
        migrations.AddField(
            model_name='dnaextractinfo',
            name='TaskProgress',
            field=models.CharField(default='DNA\u63d0\u53d6', max_length=64),
            preserve_default=False,
        ),
    ]
