# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-10-10 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnchorDxLimsApp', '0018_dnaextractinfo_prelibcon_sign'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreLibConInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64)),
                ('department', models.CharField(max_length=64)),
                ('sam_code_num', models.CharField(max_length=64)),
                ('ExperimentNumber', models.CharField(max_length=64)),
                ('DNA_Concentration', models.CharField(max_length=32)),
                ('DNA_volume', models.CharField(max_length=32)),
                ('DNA_Total', models.CharField(max_length=32)),
                ('Indexi5i7', models.CharField(max_length=32)),
                ('Quality_inspection_method', models.CharField(max_length=32)),
                ('Quality_inspection_result', models.CharField(max_length=64)),
                ('Quality_inspection_volume', models.CharField(max_length=32)),
                ('Quality_inspection_mass', models.CharField(max_length=32)),
                ('Residual_volume', models.CharField(max_length=32)),
                ('Residual_mass', models.CharField(max_length=32)),
                ('Extraction_kit_type', models.CharField(max_length=128)),
                ('Build_lib_man', models.CharField(max_length=32)),
                ('Build_lib_time', models.CharField(max_length=32)),
                ('Build_lib_remarks', models.CharField(max_length=512)),
                ('Build_lib_review_people', models.CharField(max_length=64)),
                ('Build_lib_review_Time', models.CharField(max_length=32)),
                ('Build_lib_review_Remarks', models.CharField(max_length=512)),
                ('Build_lib_review_Sign', models.CharField(max_length=16)),
                ('Build_lib_num', models.CharField(max_length=16)),
                ('TaskProgress', models.CharField(max_length=64)),
                ('PreLibCon_Sign', models.CharField(max_length=16)),
            ],
        ),
    ]
