# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-10-11 10:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AnchorDxLimsApp', '0020_auto_20171010_1909'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prelibconinfo',
            old_name='PreLibCon_Sign',
            new_name='FinalLibCon_Sign',
        ),
    ]
