# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-10-20 05:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnchorDxLimsApp', '0021_auto_20171011_1837'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinLibConInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64)),
                ('department', models.CharField(max_length=64)),
                ('sam_code_num', models.CharField(max_length=64)),
                ('ExperimentNumber', models.CharField(max_length=64)),
                ('FinLibConName', models.CharField(max_length=32)),
                ('DNA_Concentration', models.CharField(max_length=32)),
                ('DNA_volume', models.CharField(max_length=32)),
                ('DNA_Total', models.CharField(max_length=32)),
                ('Indexi5i7', models.CharField(max_length=32)),
                ('Panel', models.CharField(max_length=32)),
                ('Quality_inspection_method', models.CharField(max_length=32)),
                ('Quality_inspection_result', models.CharField(max_length=64)),
                ('Quality_inspection_volume', models.CharField(max_length=32)),
                ('Quality_inspection_mass', models.CharField(max_length=32)),
                ('Residual_volume', models.CharField(max_length=32)),
                ('Residual_mass', models.CharField(max_length=32)),
                ('Build_lib_man', models.CharField(max_length=32)),
                ('Build_lib_time', models.CharField(max_length=32)),
                ('Build_lib_remarks', models.CharField(max_length=512)),
                ('Next_TaskProgress_Man', models.CharField(max_length=64)),
                ('Next_TaskProgress_Time', models.CharField(max_length=32)),
                ('Next_TaskProgress_Remarks', models.CharField(max_length=512)),
                ('Next_TaskProgress_Sign', models.CharField(max_length=16)),
                ('Build_lib_num', models.CharField(max_length=16)),
                ('TaskProgress', models.CharField(max_length=64)),
            ],
        ),
    ]
