# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-10-20 09:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnchorDxLimsApp', '0022_finlibconinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='finlibconinfo',
            name='Build_finlib_num',
            field=models.CharField(default=1, max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='finlibconinfo',
            name='DNA_extraction_num',
            field=models.CharField(default='1', max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prelibconinfo',
            name='DNA_extraction_num',
            field=models.CharField(default='1', max_length=16),
            preserve_default=False,
        ),
    ]
