# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-10-24 07:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnchorDxLimsApp', '0023_auto_20171020_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='finlibconinfo',
            name='ComputerSeq_Sign',
            field=models.CharField(default='1', max_length=16),
            preserve_default=False,
        ),
    ]
