# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-10-30 03:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AnchorDxLimsApp', '0025_computerseqinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='computerseqinfo',
            old_name='Build_Finlib_num',
            new_name='Build_finlib_num',
        ),
    ]
