# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-10-31 03:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnchorDxLimsApp', '0026_auto_20171030_1114'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clinicalsampleinfo',
            old_name='TaskProgress',
            new_name='Next_TaskProgress',
        ),
        migrations.RenameField(
            model_name='clinicalsampleinfo',
            old_name='taskRemarks',
            new_name='Next_TaskProgress_Remarks',
        ),
        migrations.RenameField(
            model_name='clinicalsampleinfo',
            old_name='taskTime',
            new_name='Next_TaskProgress_Time',
        ),
        migrations.RenameField(
            model_name='dnaextractinfo',
            old_name='DNA_extraction_review_people',
            new_name='Next_TaskProgress',
        ),
        migrations.RenameField(
            model_name='dnaextractinfo',
            old_name='TaskProgress',
            new_name='Next_TaskProgress_Man',
        ),
        migrations.RenameField(
            model_name='dnaextractinfo',
            old_name='DNA_extraction_review_Remarks',
            new_name='Next_TaskProgress_Remarks',
        ),
        migrations.RenameField(
            model_name='dnaextractinfo',
            old_name='DNA_extraction_review_Sign',
            new_name='Next_TaskProgress_Sign',
        ),
        migrations.RenameField(
            model_name='dnaextractinfo',
            old_name='DNA_extraction_review_Time',
            new_name='Next_TaskProgress_Time',
        ),
        migrations.RenameField(
            model_name='finlibconinfo',
            old_name='TaskProgress',
            new_name='Next_TaskProgress',
        ),
        migrations.RenameField(
            model_name='prelibconinfo',
            old_name='Build_lib_review_people',
            new_name='Next_TaskProgress',
        ),
        migrations.RenameField(
            model_name='prelibconinfo',
            old_name='TaskProgress',
            new_name='Next_TaskProgress_Man',
        ),
        migrations.RenameField(
            model_name='prelibconinfo',
            old_name='Build_lib_review_Remarks',
            new_name='Next_TaskProgress_Remarks',
        ),
        migrations.RenameField(
            model_name='prelibconinfo',
            old_name='Build_lib_review_Sign',
            new_name='Next_TaskProgress_Sign',
        ),
        migrations.RenameField(
            model_name='prelibconinfo',
            old_name='Build_lib_review_Time',
            new_name='Next_TaskProgress_Time',
        ),
        migrations.RemoveField(
            model_name='clinicalsampleinfo',
            name='TaskReceiver',
        ),
        migrations.AddField(
            model_name='clinicalsampleinfo',
            name='Next_TaskProgress_Man',
            field=models.CharField(default=0, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clinicalsampleinfo',
            name='Next_TaskProgress_Sign',
            field=models.CharField(default=0, max_length=16),
            preserve_default=False,
        ),
    ]
