# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-10-31 06:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnchorDxLimsApp', '0027_auto_20171031_1150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='computerseqinfo',
            old_name='Computer_Seq_num',
            new_name='ExperimentTimes',
        ),
        migrations.RenameField(
            model_name='dnaextractinfo',
            old_name='DNA_extraction_num',
            new_name='ExperimentTimes',
        ),
        migrations.RenameField(
            model_name='finlibconinfo',
            old_name='Build_finlib_num',
            new_name='ExperimentTimes',
        ),
        migrations.RenameField(
            model_name='prelibconinfo',
            old_name='Build_lib_num',
            new_name='ExperimentTimes',
        ),
        migrations.AddField(
            model_name='clinicalsampleinfo',
            name='ExperimentTimes',
            field=models.CharField(default=1, max_length=16),
            preserve_default=False,
        ),
    ]
