# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-11-02 10:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AnchorDxLimsApp', '0028_auto_20171031_1434'),
    ]

    operations = [
        migrations.RenameField(
            model_name='finlibconinfo',
            old_name='Build_lib_num',
            new_name='Build_Prelib_num',
        ),
    ]
