# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-11-06 03:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AnchorDxLimsApp', '0029_auto_20171102_1813'),
    ]

    operations = [
        migrations.RenameField(
            model_name='computerseqinfo',
            old_name='Next_TaskProgress',
            new_name='DataPath',
        ),
    ]
