# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-11-06 08:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnchorDxLimsApp', '0030_auto_20171106_1112'),
    ]

    operations = [
        migrations.CreateModel(
            name='BioinfoDataAnalysisInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64)),
                ('department', models.CharField(max_length=64)),
                ('sam_code_num', models.CharField(max_length=64)),
                ('ExperimentNumber', models.CharField(max_length=64)),
                ('DataQquality', models.CharField(max_length=16)),
                ('Effective_sequencing_depth', models.CharField(max_length=16)),
                ('SequencingFileName', models.CharField(max_length=32)),
                ('QC_Result', models.CharField(max_length=32)),
                ('Path_To_Sorted_Deduped_Bam', models.CharField(max_length=32)),
                ('Analyser', models.CharField(max_length=32)),
                ('AnalysisTime', models.CharField(max_length=32)),
                ('AnalysisRemarks', models.CharField(max_length=512)),
                ('Next_TaskProgress_Time', models.CharField(max_length=32)),
                ('Next_TaskProgress_Remarks', models.CharField(max_length=512)),
                ('Next_TaskProgress_Sign', models.CharField(max_length=16)),
                ('DNA_extraction_num', models.CharField(max_length=16)),
                ('Build_Prelib_num', models.CharField(max_length=16)),
                ('Build_finlib_num', models.CharField(max_length=16)),
                ('Computer_Seq_num', models.CharField(max_length=16)),
                ('BioinfoResult_Sign', models.CharField(max_length=16)),
            ],
        ),
    ]
