# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-11-06 08:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnchorDxLimsApp', '0031_bioinfodataanalysisinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='bioinfodataanalysisinfo',
            name='DataAnalysis_num',
            field=models.CharField(default=1, max_length=16),
            preserve_default=False,
        ),
    ]
