# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-11-06 09:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnchorDxLimsApp', '0032_bioinfodataanalysisinfo_dataanalysis_num'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bioinfodataanalysisinfo',
            old_name='Next_TaskProgress_Remarks',
            new_name='Examine_Remarks',
        ),
        migrations.RenameField(
            model_name='bioinfodataanalysisinfo',
            old_name='Next_TaskProgress_Time',
            new_name='Examine_Time',
        ),
        migrations.AddField(
            model_name='bioinfodataanalysisinfo',
            name='Examine_Result',
            field=models.CharField(default=1, max_length=16),
            preserve_default=False,
        ),
    ]
