# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-11-07 06:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnchorDxLimsApp', '0033_auto_20171106_1751'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bioinfodataanalysisinfo',
            old_name='Next_TaskProgress_Sign',
            new_name='Report_Make_Sign',
        ),
        migrations.AddField(
            model_name='bioinfodataanalysisinfo',
            name='Report_Make_Time',
            field=models.CharField(default=0, max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bioinfodataanalysisinfo',
            name='Report_Maker',
            field=models.CharField(default=0, max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bioinfodataanalysisinfo',
            name='Report_Remarks',
            field=models.CharField(default=0, max_length=512),
            preserve_default=False,
        ),
    ]
