# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-11-07 06:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnchorDxLimsApp', '0034_auto_20171107_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='bioinfodataanalysisinfo',
            name='Report_File_Name',
            field=models.CharField(default='lol', max_length=64),
            preserve_default=False,
        ),
    ]
