# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-11-07 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnchorDxLimsApp', '0035_bioinfodataanalysisinfo_report_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='bioinfodataanalysisinfo',
            name='Medical_Examine_Remarks',
            field=models.CharField(default=0, max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bioinfodataanalysisinfo',
            name='Medical_Examine_Result',
            field=models.CharField(default=0, max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bioinfodataanalysisinfo',
            name='Medical_Examine_Sign',
            field=models.CharField(default=0, max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bioinfodataanalysisinfo',
            name='Medical_Examine_Time',
            field=models.CharField(default=0, max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bioinfodataanalysisinfo',
            name='Operate_Examine_Remarks',
            field=models.CharField(default=0, max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bioinfodataanalysisinfo',
            name='Operate_Examine_Result',
            field=models.CharField(default=0, max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bioinfodataanalysisinfo',
            name='Operate_Examine_Sign',
            field=models.CharField(default=0, max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bioinfodataanalysisinfo',
            name='Operate_Examine_Time',
            field=models.CharField(default=0, max_length=32),
            preserve_default=False,
        ),
    ]
