# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-11-13 03:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnchorDxLimsApp', '0036_auto_20171107_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='bioinfodataanalysisinfo',
            name='Invoice_Issuing_Date',
            field=models.CharField(default=0, max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bioinfodataanalysisinfo',
            name='Report_Send_Address',
            field=models.CharField(default=0, max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bioinfodataanalysisinfo',
            name='Report_Send_Date',
            field=models.CharField(default=0, max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bioinfodataanalysisinfo',
            name='Report_Send_Remarks',
            field=models.CharField(default=0, max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bioinfodataanalysisinfo',
            name='Report_Send_Sign',
            field=models.CharField(default=0, max_length=16),
            preserve_default=False,
        ),
    ]
