# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-11-14 07:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnchorDxLimsApp', '0037_auto_20171113_1144'),
    ]

    operations = [
        migrations.CreateModel(
            name='clinicalSamplePretreatment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64)),
                ('department', models.CharField(max_length=64)),
                ('sam_code_num', models.CharField(max_length=64)),
                ('ExperimentNumber', models.CharField(max_length=64)),
                ('Types_of_blood_vessel', models.CharField(max_length=16)),
                ('number_of_plasma', models.CharField(max_length=32)),
                ('Plasma_volume', models.CharField(max_length=32)),
                ('number_of_white_blood_cells', models.CharField(max_length=32)),
                ('Leukocyte_volume', models.CharField(max_length=64)),
                ('Operator', models.CharField(max_length=32)),
                ('Operating_time', models.CharField(max_length=32)),
                ('Pretreatment_remarks', models.CharField(max_length=512)),
                ('Next_TaskProgress', models.CharField(max_length=64)),
                ('Next_TaskProgress_Man', models.CharField(max_length=64)),
                ('Next_TaskProgress_Time', models.CharField(max_length=32)),
                ('Next_TaskProgress_Remarks', models.CharField(max_length=512)),
                ('Next_TaskProgress_Sign', models.CharField(max_length=16)),
                ('DNAExtract_Sign', models.CharField(max_length=16)),
            ],
        ),
    ]
