# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-11-20 03:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnchorDxLimsApp', '0038_clinicalsamplepretreatment'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicalsampleinfo',
            name='Review_Time',
            field=models.CharField(default=0, max_length=32),
            preserve_default=False,
        ),
    ]
