# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-11-20 06:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnchorDxLimsApp', '0039_clinicalsampleinfo_review_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='contractReviewInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64)),
                ('department', models.CharField(max_length=64)),
                ('sam_code_num', models.CharField(max_length=64)),
                ('ExperimentNumber', models.CharField(max_length=64)),
                ('Receivables', models.CharField(max_length=128)),
                ('ReceivablesDate', models.CharField(max_length=256)),
                ('contract_Time', models.CharField(max_length=32)),
                ('contractReviewReason', models.CharField(max_length=512)),
                ('ExperimentTimes', models.CharField(max_length=16)),
            ],
        ),
        migrations.RemoveField(
            model_name='clinicalsampleinfo',
            name='Receivables',
        ),
        migrations.RemoveField(
            model_name='clinicalsampleinfo',
            name='ReceivablesDate',
        ),
        migrations.RemoveField(
            model_name='clinicalsampleinfo',
            name='contractReviewReason',
        ),
    ]
