# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-11-20 07:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnchorDxLimsApp', '0040_auto_20171120_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicalsampleinfo',
            name='contract_Times',
            field=models.CharField(default=1, max_length=16),
            preserve_default=False,
        ),
    ]
