# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-11-27 07:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnchorDxLimsApp', '0041_clinicalsampleinfo_contract_times'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='password',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='BioinfoAnalysis',
            field=models.CharField(default=0, max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='BioinfoDataAnalysisResultReview',
            field=models.CharField(default=0, max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='BioinfoDataAnalysisTaskReview',
            field=models.CharField(default=0, max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='BioinfoReportMedicalAuditTaskReview',
            field=models.CharField(default=0, max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='BioinfoReportOperateAuditTaskReview',
            field=models.CharField(default=0, max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='BioinfoReportSendInfoTaskReview',
            field=models.CharField(default=0, max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='BioinfoReportTaskReview',
            field=models.CharField(default=0, max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='BioinfoTaskAssignment',
            field=models.CharField(default=0, max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='BusinessAffairsManagement',
            field=models.CharField(default=0, max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='ClinicalSampleRegistration',
            field=models.CharField(default=0, max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='ComSeqTaskReview',
            field=models.CharField(default=0, max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='DNAExtractTaskReview',
            field=models.CharField(default=0, max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='FinLibConTaskReview',
            field=models.CharField(default=0, max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='PreLibConTaskReview',
            field=models.CharField(default=0, max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='PretreatmentTaskReview',
            field=models.CharField(default=0, max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='ReportManagement',
            field=models.CharField(default=0, max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='SampleManagement',
            field=models.CharField(default=0, max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='clinicalExperimentalTaskAssignment',
            field=models.CharField(default=0, max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='contractManagement',
            field=models.CharField(default=0, max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='contractReview',
            field=models.CharField(default=0, max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='sampleReview',
            field=models.CharField(default=0, max_length=16),
            preserve_default=False,
        ),
    ]
