# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-11-27 09:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnchorDxLimsApp', '0042_auto_20171127_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='DefaultMark',
            field=models.CharField(default=0, max_length=16),
            preserve_default=False,
        ),
    ]
