# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-12-05 02:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnchorDxLimsApp', '0043_userinfo_defaultmark'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOperationPermissionsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64)),
                ('department', models.CharField(max_length=64)),
                ('DefaultMark', models.CharField(max_length=16)),
                ('ClinicalSampleRegistration', models.CharField(max_length=16)),
                ('sampleReview', models.CharField(max_length=16)),
                ('clinicalExperimentalTaskAssignment', models.CharField(max_length=16)),
                ('PretreatmentTaskReview', models.CharField(max_length=16)),
                ('DNAExtractTaskReview', models.CharField(max_length=16)),
                ('PreLibConTaskReview', models.CharField(max_length=16)),
                ('FinLibConTaskReview', models.CharField(max_length=16)),
                ('ComSeqTaskReview', models.CharField(max_length=16)),
                ('contractReview', models.CharField(max_length=16)),
                ('BioinfoTaskAssignment', models.CharField(max_length=16)),
                ('BioinfoDataAnalysisTaskReview', models.CharField(max_length=16)),
                ('BioinfoDataAnalysisResultReview', models.CharField(max_length=16)),
                ('BioinfoReportTaskReview', models.CharField(max_length=16)),
                ('BioinfoReportMedicalAuditTaskReview', models.CharField(max_length=16)),
                ('BioinfoReportOperateAuditTaskReview', models.CharField(max_length=16)),
                ('BioinfoReportSendInfoTaskReview', models.CharField(max_length=16)),
            ],
        ),
    ]
