# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-12-15 07:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnchorDxLimsApp', '0044_useroperationpermissionsinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='RandDSampleInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64)),
                ('department', models.CharField(max_length=64)),
                ('sam_code_num', models.CharField(max_length=64)),
                ('HospitalForInspection', models.CharField(max_length=64)),
                ('Contacts', models.CharField(max_length=32)),
                ('SamplingTime_Blood', models.CharField(max_length=32)),
                ('SamplingTime_Tissue', models.CharField(max_length=32)),
                ('Collector', models.CharField(max_length=32)),
                ('InpatientNumber', models.CharField(max_length=32)),
                ('PathologicalNumber', models.CharField(max_length=32)),
                ('CorrelationNumber', models.CharField(max_length=64)),
                ('PatientName', models.CharField(max_length=32)),
                ('PatientAge', models.CharField(max_length=16)),
                ('PatientSex', models.CharField(max_length=16)),
                ('BloodSampleType', models.CharField(max_length=16)),
                ('BloodSamplingTime', models.CharField(max_length=32)),
                ('TissueSampleSources', models.CharField(max_length=32)),
                ('TissueQuantity', models.CharField(max_length=16)),
                ('TissueType', models.CharField(max_length=16)),
                ('TissueSampleProcessing', models.CharField(max_length=32)),
                ('OperationDate', models.CharField(max_length=16)),
                ('PathologicalInfo', models.CharField(max_length=32)),
                ('TNMStaging', models.CharField(max_length=32)),
                ('Stage', models.CharField(max_length=32)),
                ('MolecularDiagnosticInfo', models.CharField(max_length=32)),
                ('Classification', models.CharField(max_length=32)),
                ('PlasmaUse', models.CharField(max_length=16)),
                ('TissueUse', models.CharField(max_length=16)),
                ('PlasmaStoragePosition', models.CharField(max_length=32)),
                ('TissueStoragePosition', models.CharField(max_length=32)),
                ('Reviewer', models.CharField(max_length=32)),
                ('ReviewTime', models.CharField(max_length=32)),
                ('ReviewRemarks', models.CharField(max_length=512)),
                ('sample_review', models.CharField(max_length=16)),
                ('task_assignment', models.CharField(max_length=16)),
                ('Next_TaskProgress', models.CharField(max_length=64)),
                ('Next_TaskProgress_Man', models.CharField(max_length=64)),
                ('Next_TaskProgress_Time', models.CharField(max_length=32)),
                ('Next_TaskProgress_Remarks', models.CharField(max_length=512)),
                ('Next_TaskProgress_Sign', models.CharField(max_length=16)),
                ('ExperimentTimes', models.CharField(max_length=16)),
            ],
        ),
    ]
