# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-12-19 03:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AnchorDxLimsApp', '0047_randdsampleinfo_tissuesamplesign'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='randdsampleinfo',
            name='task_assignment',
        ),
    ]
