# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-12-19 07:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnchorDxLimsApp', '0048_remove_randdsampleinfo_task_assignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='RandDSamplePretreatmentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64)),
                ('department', models.CharField(max_length=64)),
                ('sam_code_num', models.CharField(max_length=64)),
                ('Plasma_volume', models.CharField(max_length=16)),
                ('Division_Tube_Number', models.CharField(max_length=16)),
                ('number_of_white_blood_cells', models.CharField(max_length=32)),
                ('isHemolysis', models.CharField(max_length=16)),
                ('isFatBlood', models.CharField(max_length=16)),
                ('Type_of_blood_vessel', models.CharField(max_length=16)),
                ('Blood_sharing_time', models.CharField(max_length=16)),
                ('Pretreatment_remarks', models.CharField(max_length=512)),
                ('Next_TaskProgress', models.CharField(max_length=16)),
                ('Next_TaskProgress_Man', models.CharField(max_length=32)),
                ('Next_TaskProgress_Time', models.CharField(max_length=32)),
                ('Next_TaskProgress_Remarks', models.CharField(max_length=512)),
                ('Next_TaskProgress_Sign', models.CharField(max_length=16)),
                ('DNAExtract_Sign', models.CharField(max_length=16)),
            ],
        ),
    ]
