# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-12-19 08:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnchorDxLimsApp', '0049_randdsamplepretreatmentinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='randdsamplepretreatmentinfo',
            name='Blood_sharing_time',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='randdsamplepretreatmentinfo',
            name='Division_Tube_Number',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='randdsamplepretreatmentinfo',
            name='Plasma_volume',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='randdsamplepretreatmentinfo',
            name='Type_of_blood_vessel',
            field=models.CharField(max_length=32),
        ),
    ]
