# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-12-21 03:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnchorDxLimsApp', '0050_auto_20171219_1622'),
    ]

    operations = [
        migrations.CreateModel(
            name='RandDSampleDNAExtractInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64)),
                ('department', models.CharField(max_length=64)),
                ('sam_code_num', models.CharField(max_length=64)),
                ('DNASampleName', models.CharField(max_length=32)),
                ('PlasmaVolume', models.CharField(max_length=32)),
                ('QuantitativeMethod', models.CharField(max_length=32)),
                ('DNA_Concentration', models.CharField(max_length=32)),
                ('DNA_volume', models.CharField(max_length=32)),
                ('DNA_Total', models.CharField(max_length=32)),
                ('A260_A280', models.CharField(max_length=32)),
                ('A260_A230', models.CharField(max_length=32)),
                ('Extraction_kit_type', models.CharField(max_length=128)),
                ('DNA_extraction_time', models.CharField(max_length=32)),
                ('Quality_inspection_method', models.CharField(max_length=32)),
                ('Quality_inspection_result', models.CharField(max_length=64)),
                ('Glue_map_link', models.CharField(max_length=64)),
                ('DNA_storage_location', models.CharField(max_length=32)),
                ('DNA_extraction_Operator', models.CharField(max_length=32)),
                ('DNA_extraction_remarks', models.CharField(max_length=512)),
                ('Next_TaskProgress', models.CharField(max_length=64)),
                ('Next_TaskProgress_Man', models.CharField(max_length=64)),
                ('Next_TaskProgress_Time', models.CharField(max_length=32)),
                ('Next_TaskProgress_Remarks', models.CharField(max_length=512)),
                ('Next_TaskProgress_Sign', models.CharField(max_length=16)),
                ('ExperimentTimes', models.CharField(max_length=16)),
                ('PreLibCon_Sign', models.CharField(max_length=16)),
            ],
        ),
    ]
