# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-12-21 06:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnchorDxLimsApp', '0051_randdsamplednaextractinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='randdsamplednaextractinfo',
            name='Next_TaskProgress',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='randdsamplednaextractinfo',
            name='Next_TaskProgress_Man',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='randdsamplednaextractinfo',
            name='Quality_inspection_result',
            field=models.CharField(max_length=32),
        ),
    ]
