# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-12-21 09:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnchorDxLimsApp', '0052_auto_20171221_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicalsampleinfo',
            name='Pretreatment_Sign',
            field=models.CharField(default=1, max_length=16),
            preserve_default=False,
        ),
    ]
