# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-12-22 01:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnchorDxLimsApp', '0053_clinicalsampleinfo_pretreatment_sign'),
    ]

    operations = [
        migrations.AddField(
            model_name='randdsampleinfo',
            name='Pretreatment_Sign',
            field=models.CharField(default=0, max_length=16),
            preserve_default=False,
        ),
    ]
