# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-12-22 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnchorDxLimsApp', '0055_randdsampleinfo_dnaextract_sign'),
    ]

    operations = [
        migrations.CreateModel(
            name='RandDSamplePreLibConInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64)),
                ('department', models.CharField(max_length=64)),
                ('sam_code_num', models.CharField(max_length=64)),
                ('PreLibConName', models.CharField(max_length=64)),
                ('InitialAmountOfTransformation', models.CharField(max_length=32)),
                ('InitialQuantityOfPreLibCon', models.CharField(max_length=32)),
                ('DNA_Concentration', models.CharField(max_length=32)),
                ('DNA_volume', models.CharField(max_length=32)),
                ('DNA_Total', models.CharField(max_length=32)),
                ('Index_i5', models.CharField(max_length=32)),
                ('Index_i7', models.CharField(max_length=32)),
                ('Build_lib_method', models.CharField(max_length=128)),
                ('Build_lib_time', models.CharField(max_length=32)),
                ('PreLibCon_storage_location', models.CharField(max_length=32)),
                ('Build_lib_man', models.CharField(max_length=32)),
                ('Quality_inspection_result', models.CharField(max_length=64)),
                ('Glue_map_link', models.CharField(max_length=64)),
                ('ConversionKitNumber', models.CharField(max_length=32)),
                ('NumberOfLibraryKit', models.CharField(max_length=32)),
                ('Build_lib_remarks', models.CharField(max_length=512)),
                ('Next_TaskProgress', models.CharField(max_length=64)),
                ('Next_TaskProgress_Man', models.CharField(max_length=64)),
                ('Next_TaskProgress_Time', models.CharField(max_length=32)),
                ('Next_TaskProgress_Remarks', models.CharField(max_length=512)),
                ('Next_TaskProgress_Sign', models.CharField(max_length=16)),
                ('DNA_extraction_num', models.CharField(max_length=16)),
                ('ExperimentTimes', models.CharField(max_length=16)),
                ('FinalLibCon_Sign', models.CharField(max_length=16)),
            ],
        ),
    ]
