# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-12-22 07:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AnchorDxLimsApp', '0056_randdsampleprelibconinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='randdsampleprelibconinfo',
            old_name='DNA_Concentration',
            new_name='Concentration',
        ),
    ]
