# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-01-02 06:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnchorDxLimsApp', '0058_auto_20171225_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='RandDComSeqInfoInputHomePage',
            field=models.CharField(default=0, max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='RandDDNAExtractInfoInputHomePage',
            field=models.CharField(default=0, max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='RandDExperimentalTaskAssignmentHomePage',
            field=models.CharField(default=0, max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='RandDFinLibConInfoInputHomePage',
            field=models.CharField(default=0, max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='RandDPreLibConInfoInputHomePage',
            field=models.CharField(default=0, max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='RandDPretreatmentInfoInputHomePage',
            field=models.CharField(default=0, max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='RandDSampleInfoInputHomePage',
            field=models.CharField(default=0, max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='RandDSampleReviewHomePage',
            field=models.CharField(default=0, max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='projectManagement',
            field=models.CharField(default=0, max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useroperationpermissionsinfo',
            name='RandDComSeqInfoInputHomePage',
            field=models.CharField(default=0, max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useroperationpermissionsinfo',
            name='RandDDNAExtractInfoInputHomePage',
            field=models.CharField(default=0, max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useroperationpermissionsinfo',
            name='RandDExperimentalTaskAssignmentHomePage',
            field=models.CharField(default=0, max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useroperationpermissionsinfo',
            name='RandDFinLibConInfoInputHomePage',
            field=models.CharField(default=0, max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useroperationpermissionsinfo',
            name='RandDPreLibConInfoInputHomePage',
            field=models.CharField(default=0, max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useroperationpermissionsinfo',
            name='RandDPretreatmentInfoInputHomePage',
            field=models.CharField(default=0, max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useroperationpermissionsinfo',
            name='RandDSampleInfoInputHomePage',
            field=models.CharField(default=0, max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useroperationpermissionsinfo',
            name='RandDSampleReviewHomePage',
            field=models.CharField(default=0, max_length=16),
            preserve_default=False,
        ),
    ]
