# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-01-03 07:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnchorDxLimsApp', '0059_auto_20180102_1402'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSystemMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sender', models.CharField(max_length=64)),
                ('Receiver', models.CharField(max_length=64)),
                ('Time', models.CharField(max_length=32)),
                ('Title', models.CharField(max_length=128)),
                ('Message', models.CharField(max_length=512)),
                ('ReadingState', models.CharField(max_length=16)),
            ],
        ),
    ]
