# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-01-04 03:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnchorDxLimsApp', '0060_usersystemmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicalsampleinfo',
            name='ContractAuditor',
            field=models.CharField(default=0, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clinicalsampleinfo',
            name='SampleAuditor',
            field=models.CharField(default=0, max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clinicalsampleinfo',
            name='CollectSamplesDate',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='clinicalsampleinfo',
            name='ExperimentNumber',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='clinicalsampleinfo',
            name='Pathological_diagnosis',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='clinicalsampleinfo',
            name='PatientAddress',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='clinicalsampleinfo',
            name='PatientAge',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='clinicalsampleinfo',
            name='PatientSex',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='clinicalsampleinfo',
            name='cancer_type',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='clinicalsampleinfo',
            name='clinical_diagnosis',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='clinicalsampleinfo',
            name='detected_gene_name',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='clinicalsampleinfo',
            name='detected_gene_result',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='clinicalsampleinfo',
            name='detected_gene_time',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='clinicalsampleinfo',
            name='detection_type',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='clinicalsampleinfo',
            name='family_history',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='clinicalsampleinfo',
            name='infection_history',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='clinicalsampleinfo',
            name='product_name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='clinicalsampleinfo',
            name='sample_source',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='clinicalsampleinfo',
            name='sample_type_text',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='clinicalsampleinfo',
            name='treatment_history_chem',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='clinicalsampleinfo',
            name='treatment_history_surgery',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='clinicalsampleinfo',
            name='treatment_history_therapy',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='clinicalsampleinfo',
            name='treatment_hospital',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='clinicalsampleinfo',
            name='tubercle_distribution',
            field=models.CharField(max_length=64),
        ),
    ]
