# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-01-09 07:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnchorDxLimsApp', '0062_clinicalsampleinfo_taskassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='computerseqinfo',
            name='BioTaskAssignment',
            field=models.CharField(default=0, max_length=64),
            preserve_default=False,
        ),
    ]
