# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-01-09 09:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AnchorDxLimsApp', '0064_auto_20180109_1624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='randdsampleinfo',
            name='Reviewer',
        ),
    ]
