# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-01-11 04:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AnchorDxLimsApp', '0067_clinicalsampleinfo_dnaextract_sign'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinicalsampleinfo',
            name='DNAExtract_Sign',
        ),
    ]
