# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-01-12 03:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnchorDxLimsApp', '0069_clinicalsampleinfo_dnaextract_sign'),
    ]

    operations = [
        migrations.AddField(
            model_name='randdsamplecomputerseqinfo',
            name='BioTaskAssignment',
            field=models.CharField(default=0, max_length=64),
            preserve_default=False,
        ),
    ]
