# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-01-12 07:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnchorDxLimsApp', '0072_remove_bioinfodataanalysisinfo_samplesource'),
    ]

    operations = [
        migrations.AddField(
            model_name='bioinfodataanalysisinfo',
            name='ReportMakeTask_Man',
            field=models.CharField(default=0, max_length=32),
            preserve_default=False,
        ),
    ]
