# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-02-05 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnchorDxLimsApp', '0075_auto_20180115_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicalsampleinfo',
            name='ReviewResult',
            field=models.CharField(default=0, max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='randdsampleinfo',
            name='ReviewResult',
            field=models.CharField(default=0, max_length=16),
            preserve_default=False,
        ),
    ]
